import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {createTown,LOCATIONS} from './town.js';
const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
let day=1,place='statue',tab='place',town,region='',renderer,scene,camera,controls,flight=null,isFlat=false,moving=true,tour=false,paused=false,tourTime=0,elapsed=0,last=0,modelOnly=false,failed=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const cache=new Map(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const regionFor=i=>i>=10?'transit':DAYS[i].scene;
const labelNodes=[];
function airportName(){return day===5?'Buffalo Niagara International Airport':day===8?'Newark Liberty International Airport':day===9||day===10?'Quebec City Jean Lesage International Airport':day===11?'Narita International Airport':day===4||day===6?'John F Kennedy International Airport':'LaGuardia Airport';}
function mapQuery(){return place==='airport'?airportName():PLACES[place].query;}
function placeInfo(){const p=PLACES[place],source=p.source&&SOURCES[p.source];return `<p class="eyebrow">${DAYS[day].city} / ${DAYS[day].stops.includes(place)?'오늘의 장소':'지역 둘러보기'}</p><h2>${escape(p.name)}</h2><p class="introText">${escape(p.desc)}</p><h3>현장에서 볼 포인트</h3><p>${escape(DETAILS[place]||p.tip)}</p><h3>방문 전 확인</h3><p>${escape(p.tip)}</p><dl><dt>추천 체류시간</dt><dd>${escape(p.duration)}</dd><dt>비용 · 예약 상태</dt><dd>${escape(p.price)}</dd></dl><div class="panelLinks">${source?`<a href="${source[1]}" target="_blank" rel="noopener noreferrer">공식 안내 ↗</a>`:''}<a href="${maps(mapQuery())}" target="_blank" rel="noopener noreferrer">실제 지도 ↗</a></div><small>관광 예약은 유엔만 사용자 확인. 나머지는 계획·선택 항목입니다. 공식 안내 확인 2026.09.09, 실제 방문일 재확인.</small>`;}
const DETAILS={statue:'별 모양 기단 위의 녹색 동상, 오른손의 횃불과 왼손의 서판을 찾아보세요. 섬에서는 동상 자체뿐 아니라 물 건너 맨해튼의 스카이라인도 함께 보입니다.',bridge:'석조 탑과 촘촘한 현수 케이블이 만드는 반복을 눈여겨보세요. 덤보 강변에서는 다리와 맨해튼을 한 화면에 담을 수 있습니다.',met:'계단과 고전적인 정면을 지나면 시대와 지역이 완전히 다른 전시가 이어집니다. 덴두르 신전과 관심 있는 전시 하나를 고르면 아이와 함께 보기에 덜 지칩니다.',frontenac:'급경사의 녹색 지붕과 여러 탑이 겹쳐진 실루엣이 구시가의 중심입니다. 뒤프랭 테라스에서는 강과 아래 마을을 함께 내려다보세요.',falls:'폭포의 폭과 굽이치는 형태, 가장자리에서 피어오르는 물안개가 핵심입니다. 소리와 바람도 풍경의 일부이니 여유 있게 멈춰 보세요.',petit:'작은 간판, 경사진 지붕, 좁은 돌길이 이어지는 동네입니다. 사진만 찍고 지나가기보다 카페 한 곳에서 잠깐 쉬어 가세요.',un:'넓은 유리 정면의 사무국 건물과 여러 나라의 국기가 대비됩니다. 투어는 현장 회의 상황에 따라 방문 구역이 바뀔 수 있습니다.',grand:'메인홀의 별자리 천장과 중앙 시계를 찾아보세요. 통근객의 이동을 방해하지 않는 가장자리에서 천천히 둘러봅니다.',memorial:'건물 대신 비어 있는 두 공간과 그 안으로 흐르는 물을 바라보는 추모 장소입니다. 사진 촬영보다 조용히 머무는 시간을 먼저 권합니다.',vessel:'반복되는 계단과 층마다 달라지는 시선을 관찰해 보세요. 외관 감상만으로도 형태의 특징이 잘 드러납니다.',time:'서로 다른 크기의 전광판과 빌딩 사이를 흐르는 사람들의 움직임이 만드는 풍경입니다. 도착 첫날 무리해서 찾기보다 충분히 쉬고 방문하세요.'};
function scheduleHTML(d){return `<p class="eyebrow">${d.date} ${d.weekday} · 현지 시각</p><h2>${escape(d.title)}</h2><p class="warning">${escape(d.note)}</p>${d.events.map(([t,h,p])=>`<article class="event"><time>${escape(t)}</time><h3>${escape(h)}</h3><p>${escape(p)}</p></article>`).join('')}`;}
function updatePanel(){const sc=$('#panelBody').scrollTop;$('#panelBody').innerHTML=tab==='place'?placeInfo():scheduleHTML(DAYS[day]);$('#panelBody').scrollTop=tab==='place'?0:sc;$('#placeTab').setAttribute('aria-pressed',tab==='place');$('#scheduleTab').setAttribute('aria-pressed',tab==='schedule');$('#mapLink').href=maps(mapQuery());$('#tourPlace').textContent=`${DAYS[day].date} · ${PLACES[place].name}`;}
function openPanel(){document.body.classList.remove('panelClosed');$('#infoButton').setAttribute('aria-pressed','true');}
function renderMini(){const ids=DAYS[day].stops;const points=ids.map((id,i)=>[38+i*62,85+(i%2?-25:8)]);$('#routeMap').innerHTML=`<rect width="280" height="155" rx="8" fill="#dfe5d2"/><path d="M0 113 Q70 61 140 117 T280 94 L280 155H0Z" fill="#a6cdd0"/><path d="M10 28H270 M10 52H270 M30 10V130 M92 10V130 M160 10V130 M230 10V130" stroke="#f2ecd9" stroke-width="9"/><polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#a7734c" stroke-dasharray="4 4" stroke-width="2"/>`+ids.map((id,i)=>`<g data-mini="${id}" role="button" tabindex="0" aria-label="${escape(PLACES[id].name)}"><circle cx="${points[i][0]}" cy="${points[i][1]}" r="15" fill="${id===place?'#b16e42':'#244e55'}" stroke="white" stroke-width="2"/><text x="${points[i][0]}" y="${points[i][1]+5}" fill="white" text-anchor="middle" font-size="13">${i+1}</text></g>`).join('');}
function refreshSelection(){document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.place===place));renderMini();updatePanel();$('#announcement').textContent=`${DAYS[day].date} ${PLACES[place].name} 선택`;}
function selectPlace(id,animate=true,manual=true){if(!PLACES[id])return;if(manual&&tour)pauseTour();place=id;tab='place';openPanel();refreshSelection();if(animate)focusPlace(id);}
function renderDay(i,focus=true,manual=true){day=Math.max(0,Math.min(11,i));if(manual&&tour)pauseTour();const d=DAYS[day];place=d.stops[0];$('#dayNumber').textContent=String(day+1).padStart(2,'0');$('#cityName').textContent=`${d.date} ${d.weekday} · ${d.city}`;$('#dayTitle').textContent=d.title;$('#routeText').textContent=d.stops.map(id=>PLACES[id].name).join(' → ');$('#dates').innerHTML=DAYS.map((x,j)=>`<button data-day="${j}" aria-label="${x.date} ${x.weekday} ${x.title}" aria-pressed="${day===j}"><b>${String(j+1).padStart(2,'0')}</b><small>${x.date}</small></button>`).join('');$('#prevDay').disabled=day===0;$('#nextDay').disabled=day===11;$('#placeChips').innerHTML=d.stops.map((id,j)=>`<button data-place="${id}" aria-pressed="${id===place}">${j+1} ${escape(PLACES[id].name)}</button>`).join('');switchRegion(regionFor(day));refreshSelection();if(focus)focusPlace(place);const current=$(`[data-day="${day}"]`);current?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});}
function switchRegion(r){if(r===region)return;region=r;if(!cache.has(r))cache.set(r,createTown(r));if(town&&scene)scene.remove(town);town=cache.get(r);if(scene)scene.add(town);$('#nearby').innerHTML=Object.keys(LOCATIONS[r]).map(id=>`<button data-place="${id}">${escape(PLACES[id].name)}</button>`).join('');$('#labels').replaceChildren();labelNodes.length=0;Object.keys(LOCATIONS[r]).forEach(id=>{const b=document.createElement('button');b.className='landmarkLabel';b.dataset.place=id;b.textContent=PLACES[id].name;b.setAttribute('aria-label',`${PLACES[id].name}로 카메라 이동`);$('#labels').append(b);labelNodes.push({id,el:b,point:town.userData.nodes[id].clone()});});if(failed)drawFallback();}
function fly(target,zoom){if(!camera||!controls)return;const offset=isFlat?new THREE.Vector3(0,1000,.1):new THREE.Vector3(530,650,720);const dest=target.clone().add(offset);flight={start:performance.now(),duration:reduced?0:1250,fromPos:camera.position.clone(),toPos:dest,fromTarget:controls.target.clone(),toTarget:target,fromZoom:camera.zoom,toZoom:zoom};if(reduced){camera.position.copy(dest);controls.target.copy(target);camera.zoom=zoom;camera.updateProjectionMatrix();controls.update();flight=null;}}
function focusPlace(id){if(failed){drawFallback();return;}const p=town?.userData.nodes[id];if(p)fly(p.clone().add(new THREE.Vector3(0,id==='statue'?40:22,0)),innerWidth<700?1.4:1.9);}
function overall(){fly(new THREE.Vector3(0,0,0),innerWidth<700?.5:.85);}
function drawFallback(){const ids=Object.keys(LOCATIONS[region]);$('#fallback').hidden=false;$('#labels').hidden=true;$('#fallback').innerHTML=`<p>2D 탐색 · 3D 미지원 환경에서도 모든 일정을 볼 수 있습니다.</p><div>${ids.map(id=>`<button data-place="${id}" aria-pressed="${id===place}"><span>${PLACES[id].kind==='falls'?'≋':PLACES[id].kind==='plane'?'✈':'▥'}</span>${escape(PLACES[id].name)}</button>`).join('')}</div>`;}
function initScene(){try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#dfe8e9');renderer.outputColorSpace=THREE.SRGBColorSpace;$('#world').prepend(renderer.domElement);scene=new THREE.Scene();scene.background=new THREE.Color('#dfe8e9');camera=new THREE.OrthographicCamera(-400,400,300,-300,.1,5000);camera.position.set(530,650,720);camera.zoom=1.25;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minZoom=.4;controls.maxZoom=4;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.05;controls.target.set(-50,15,0);controls.update();controls.addEventListener('start',()=>{flight=null;if(tour)pauseTour();});scene.add(new THREE.HemisphereLight('#fffdf8','#a7b7ac',1.8));const sun=new THREE.DirectionalLight('#ffffff',2.1);sun.position.set(-350,750,400);sun.castShadow=true;sun.shadow.mapSize.set(innerWidth<700?1024:2048,innerWidth<700?1024:2048);Object.assign(sun.shadow.camera,{left:-720,right:720,top:720,bottom:-720,near:1,far:1800});sun.shadow.normalBias=1;sun.shadow.bias=-.0001;sun.target.position.set(0,0,0);scene.add(sun,sun.target);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();failed=true;drawFallback();$('#loading').hidden=true;});let down;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(town.userData.pickables,false).find(h=>h.object.userData.ids[h.instanceId]);if(hit)selectPlace(hit.object.userData.ids[hit.instanceId]);});resize();}catch(e){failed=true;console.warn('WebGL unavailable; using accessible 2D fallback',e.message);}$('#loading').hidden=true;}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight;camera.left=-300*aspect;camera.right=300*aspect;camera.top=300;camera.bottom=-300;camera.updateProjectionMatrix();}
function frame(t){requestAnimationFrame(frame);const dt=Math.min((t-last)/1000,.1);last=t;if(document.hidden)return;if(moving&&!reduced)elapsed+=dt;if(town)town.userData.animate(elapsed);if(flight){const p=Math.min((t-flight.start)/Math.max(flight.duration,1),1),e=p*p*(3-2*p);camera.position.lerpVectors(flight.fromPos,flight.toPos,e);controls.target.lerpVectors(flight.fromTarget,flight.toTarget,e);camera.zoom=THREE.MathUtils.lerp(flight.fromZoom,flight.toZoom,e);camera.updateProjectionMatrix();if(p===1)flight=null;}if(controls)controls.update();if(renderer&&!failed){renderer.render(scene,camera);labelNodes.forEach(({point,el,id})=>{const p=point.clone();p.y=id==='statue'?160:id==='summit'?205:id==='frontenac'?150:70;p.project(camera);const x=(p.x+1)*innerWidth/2,y=(1-p.y)*innerHeight/2;el.style.transform=`translate(-50%,-100%) translate(${x}px,${y}px)`;el.hidden=p.z>1||x<0||x>innerWidth||y<0||y>innerHeight||(!DAYS[day].stops.includes(id)&&id!==place);});}if(tour&&!paused){tourTime+=dt;$('#tourProgress').value=tourTime/Number($('#dwell').value);if(tourTime>=Number($('#dwell').value))advanceTour();}}
function pauseTour(){paused=true;$('#pauseTour').textContent='▶ 계속';}
function advanceTour(){tourTime=0;const ids=DAYS[day].stops,n=ids.indexOf(place);if(n<ids.length-1)selectPlace(ids[n+1],true,false);else if(day<11)renderDay(day+1,true,false);else stopTour();}
function stopTour(){tour=false;paused=false;tourTime=0;$('#tourBox').hidden=true;$('#tourButton').textContent='▶ 자동 투어';}
function toggleTour(){if(tour)return stopTour();tour=true;paused=false;tourTime=0;$('#tourBox').hidden=false;$('#tourButton').textContent='■ 투어 종료';$('#pauseTour').textContent='Ⅱ 일시정지';selectPlace(DAYS[day].stops.includes(place)?place:DAYS[day].stops[0],true,false);}
function bind(){document.addEventListener('keydown',e=>{const b=e.target.closest('button[data-place],button[data-day]');if(b&&['Enter',' '].includes(e.key)){e.preventDefault();b.click();}});document.addEventListener('click',e=>{const p=e.target.closest('[data-place]');if(p)selectPlace(p.dataset.place);const b=e.target.closest('[data-day]');if(b){const i=Number(b.dataset.day);renderDay(i);$(`[data-day="${i}"]`).focus({preventScroll:true});}const m=e.target.closest('[data-mini]');if(m)selectPlace(m.dataset.mini);});$('#routeMap').addEventListener('keydown',e=>{if(e.target.dataset.mini&&['Enter',' '].includes(e.key)){e.preventDefault();selectPlace(e.target.dataset.mini);}});$('#prevDay').onclick=()=>renderDay(day-1);$('#nextDay').onclick=()=>renderDay(day+1);$('#placeTab').onclick=()=>{tab='place';updatePanel();};$('#scheduleTab').onclick=()=>{tab='schedule';updatePanel();};$('#closePanel').onclick=()=>{document.body.classList.add('panelClosed');$('#infoButton').setAttribute('aria-pressed','false');$('#infoButton').focus();};$('#infoButton').onclick=()=>{if(document.body.classList.contains('panelClosed'))openPanel();else $('#closePanel').click();};$('#zoomIn').onclick=()=>{if(camera){camera.zoom=Math.min(4,camera.zoom*1.2);camera.updateProjectionMatrix();flight=null;}};$('#zoomOut').onclick=()=>{if(camera){camera.zoom=Math.max(.4,camera.zoom/1.2);camera.updateProjectionMatrix();flight=null;}};$('#resetView').onclick=()=>focusPlace(place);$('#overview').onclick=overall;$('#flatButton').onclick=()=>{isFlat=!isFlat;$('#flatButton').setAttribute('aria-pressed',isFlat);$('#flatButton').textContent=isFlat?'3D':'2D';focusPlace(place);};$('#peopleButton').onclick=()=>{moving=!moving;$('#peopleButton').textContent=moving?'사람 멈춤':'사람 움직임';$('#peopleButton').setAttribute('aria-pressed',moving);};$('#modelButton').onclick=()=>{modelOnly=!modelOnly;document.body.classList.toggle('modelOnly',modelOnly);$('#modelButton').setAttribute('aria-pressed',modelOnly);$('#modelButton').textContent=modelOnly?'안내 다시 보기':'모형만 보기';};$('#foldMap').onclick=()=>{const b=$('#miniBody');b.hidden=!b.hidden;$('#foldMap').textContent=b.hidden?'펼치기 ＋':'접기 −';$('#foldMap').setAttribute('aria-expanded',!b.hidden);};$('#tourButton').onclick=toggleTour;$('#endTour').onclick=stopTour;$('#pauseTour').onclick=()=>{paused=!paused;$('#pauseTour').textContent=paused?'▶ 계속':'Ⅱ 일시정지';};$('#nextStop').onclick=advanceTour;$('#guideButton').onclick=()=>$('#guide').showModal();$('#closeGuide').onclick=()=>$('#guide').close();$('#guide').addEventListener('click',e=>{if(e.target===$('#guide'))$('#guide').close();});$('#printButton').onclick=()=>window.print();window.addEventListener('resize',resize);}
function fillGuide(){$('#guideContent').innerHTML=`<p class="warning">계획은 2026년 10/2~13, 엄마 + 만 13세 아들 기준입니다. 시각은 모두 현지 기준. 상세 숙소와 항공편·예약번호는 공개본에 넣지 않았습니다.</p><h3>사용법</h3><p>건물·이름표·장소 버튼을 누르면 카메라가 이동합니다. 드래그로 회전, 휠·핀치로 확대, 우클릭·두 손가락으로 이동합니다. 자동 투어는 현재 날짜부터 여행 끝까지 진행하며 언제든 일시정지할 수 있습니다.</p><h3>지도와 모형의 차이</h3><p>자체 제작한 관광용 3D 디오라마입니다. 실제 축척·방향·도로·건물의 실측 복제가 아닙니다. 왼쪽 아래도 방문 순서 개념도이며, 정확한 위치는 ‘실제 지도’ 링크에서 확인하세요. 지도 타일·새 API 호출 없이 작동합니다.</p>${CHECKS.map(([h,p])=>`<h3>${escape(h)}</h3><p>${escape(p)}</p>`).join('')}<h3>덜 걷고 싶다면 · 선택 일정</h3>${ALTERNATIVES.map(([h,w,p])=>`<h4>${escape(h)} · ${escape(w)}</h4><p>${escape(p)}</p>`).join('')}<h3>비용 예시 · 총예산 아님</h3><p>MET 성인 $30 + 학생 $17, MoMA $30 + $0, Whitney $30 + $0 → 미술관 소계 US$${30+17+30+30}. MET 학생 요금 불인정 시 US$${30*4}. 항공·숙소·교통·식비·다른 관광 제외.</p><p>Journey Behind the Falls 13세 이상 CA$33 × 2명 × 1.13(HST) = CA$${(33*2*1.13).toFixed(2)}. 10월 운영·실제 결제액 재확인. USD와 CAD를 환율 없이 합치지 않습니다.</p><h3>출처 · 확인 2026-09-09</h3><ul>${Object.values(SOURCES).map(([n,u])=>`<li><a href="${u}" target="_blank" rel="noopener noreferrer">${n} ↗</a></li>`).join('')}</ul><p>일정은 사용자 확인·계획용 추정·공식 확인을 구분했습니다. 실시간 정보나 자동 예약 서비스가 아닙니다. noindex는 접근제어가 아니며 링크를 아는 사람은 볼 수 있습니다.</p><p>3D 엔진: <a href="vendor/LICENSE-three.txt">Three.js · MIT License</a>. 도시·모형은 자체 제작. 외부 사진·음원·API 없음. 배경음은 브라우저가 합성하며 입장 시 자동재생을 시도합니다. 차단되면 첫 클릭·터치 또는 키보드 입력으로 시작합니다. 음악 버튼으로 끄기·다시 켜기와 음량 조절이 가능합니다. 다른 탭으로 이동하면 음악이 꺼집니다. <a href="../nyqc/">기존 문서형 안내서 ↗</a></p>`;$('#printAll').innerHTML='<h1>두 사람의 가을 · 2026 전체 일정</h1>'+DAYS.map(d=>`<section>${scheduleHTML(d)}</section>`).join('')+'<section><h2>예약·준비</h2>'+CHECKS.map(([h,p])=>`<h3>${escape(h)}</h3><p>${escape(p)}</p>`).join('')+'</section>';}
initScene();fillGuide();bind();renderDay(1,true);requestAnimationFrame(frame);
// Read-only diagnostics for deployment verification, not a user-facing feature.
window.travelDiagnostics=()=>({day,place,region,webgl:!failed,flat:isFlat,tour,paused,moving,flight:!!flight,canvas:!!renderer,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,landmarks:labelNodes.length,localLibraries:true});
