const SOURCES={met:['MET 관람 안내','https://www.metmuseum.org/plan-your-visit'],moma:['MoMA 관람 안내','https://www.moma.org/visit/'],un:['유엔 방문 FAQ','https://www.un.org/en/visit/faq'],untour:['유엔 가이드 투어','https://www.un.org/en/visit/tour'],statue:['NPS 자유의여신상 방문 안내','https://www.nps.gov/stli/planyourvisit/index.htm'],memorial:['9/11 방문 안내','https://www.911memorial.org/visit'],whitney:['Whitney 관람 안내','https://whitney.org/visit'],summit:['SUMMIT 공식 티켓','https://summitov.com/tickets/'],vessel:['Vessel 공식 안내','https://www.vesselnyc.com/'],nypl:['NYPL 본관','https://www.nypl.org/locations/schwarzman'],cards:['Bleecker Trading 매장 안내','https://bleeckertrading.com/'],quebec:['퀘벡 관광청 · 구시가','https://www.quebec-cite.com/en/old-quebec'],falls:['Niagara Parks · Journey Behind the Falls','https://www.niagaraparks.com/visit/attractions/journey-behind-the-falls/'],minor:['캐나다 정부 · 미성년자 동반 여행','https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/minor-children-travelling-canada.html'],mj:['MJ 공식 사이트','https://mjthemusical.com/']};
const PLACES={
airport:{name:'공항 · 이동의 날',kind:'plane',desc:'오늘은 다음 도시로 안전하게 이동하는 것이 첫 번째 일정입니다. 항공 시각은 사용자 제공값이며 예약 원문과의 대조는 남아 있습니다.',duration:'항공·공항 수속 중심',price:'예약 내역 기준',tip:'짐 찾기·렌터카 반납·보안검색은 비행시간에 포함되지 않습니다.',query:'LaGuardia Airport New York',source:null},
time:{name:'타임스퀘어',kind:'tower',desc:'밤에도 환한 전광판 사이를 천천히 걷습니다. 도착일이 아니라 충분히 쉬고 난 뒤 뉴욕의 첫 장면으로 만나요.',duration:'30–45분 · 계획용',price:'야외 무료 / 식사 별도',tip:'소지품은 앞으로, 거리 캐릭터·사진 제안은 비용을 먼저 확인하세요.',query:'Times Square New York',source:null},
statue:{name:'자유의여신상',kind:'statue',desc:'뉴욕 항구에서 만나는 자유의 상징. 기본안은 섬 상륙 페리, 페데스탈은 확보되면 추가합니다. 왕관은 과거 매진 기록만 있으며 현재 재고는 미확인입니다.',duration:'한 섬 기준 약 3–4시간 · 대기 포함 추정',price:'공식 날짜별 티켓 확인',tip:'NPS가 안내하는 유일한 공식 운항사는 Statue City Cruises. 표의 시각은 출항시각이 아니라 보안검색 줄에 서는 시각입니다. 엘리스섬까지 방문하면 오후 일정을 줄이세요.',query:'The Battery Statue City Cruises New York',source:'statue'},
wall:{name:'월가 · 황소 · 소녀상',kind:'tower',desc:'금융가를 짧게 둘러보고 황소와 Fearless Girl을 찾는 산책. 두 조각상이 같은 자리에 있다고 생각하지 말고 각각 지도에서 확인하세요.',duration:'45–60분 · 계획용',price:'야외 관람 무료',tip:'월가–Bowling Green–NYSE 주변 도보. 혼잡하면 사진 대기를 줄이세요.',query:'Fearless Girl New York Stock Exchange',source:null},
memorial:{name:'9/11 메모리얼',kind:'memorial',desc:'폭포가 흐르는 두 개의 추모 공간에서 잠시 멈춥니다. 기본 일정은 야외 메모리얼이며, 실내 박물관은 선택입니다.',duration:'야외 40–60분 / 박물관 추가 90분 이상',price:'야외 무료 · 박물관 별도',tip:'공식: 야외 매일 08–20시. 박물관 수–월 및 일부 화요일 09–19시, 마지막 입장 17:30. 전시 주제가 무거우므로 아이의 반응을 살펴 쉬세요.',query:'9/11 Memorial New York',source:'memorial'},
bridge:{name:'브루클린 브리지 · 덤보',kind:'bridge',desc:'다리를 건너 강 건너의 스카이라인을 봅니다. 걷기가 부담되면 덤보로 바로 이동해 워터프런트만 산책해도 좋습니다.',duration:'90–120분 · 휴식 포함 추정',price:'야외 무료 · 교통 별도',tip:'다리 전체 걷기와 덤보 산책을 모두 하면 보행량이 늘어납니다. 비·강풍에는 실내 일정으로 교체하세요.',query:'DUMBO Brooklyn Bridge Park New York',source:null},
whitney:{name:'휘트니 미술관',kind:'museum',desc:'미국 현대미술을 만나는 시간. 브루클린에서 이동 후 점심을 먹고, 하이라인과 연결합니다.',duration:'90분 · 계획용',price:'성인 US$30 / 25세 이하 무료',tip:'공식: 화요일 휴관, 일요일 10:30–18시. 아들은 무료이나 입장권은 확인하세요. 피곤하면 내부 관람 대신 하이라인만 선택합니다.',query:'Whitney Museum 99 Gansevoort Street New York',source:'whitney'},
vessel:{name:'하이라인 · Vessel',kind:'vessel',desc:'고가 공원의 일부 구간을 걸어 허드슨야드로. Vessel은 외관 감상을 기본으로 하고 내부 입장은 선택합니다.',duration:'60–90분 · 계획용',price:'외관·공원 무료 / Vessel 입장 US$14부터',tip:'현재 공식 사이트에 엘리베이터 운행 중단 안내가 있습니다. 계단·운영 상황을 방문 전 다시 확인하세요.',query:'Vessel Hudson Yards New York',source:'vessel'},
met:{name:'메트로폴리탄 미술관',kind:'museum',desc:'덴두르 신전과 마음에 드는 전시 한 곳만 골라도 충분합니다. 전관 완주보다 좋아하는 작품을 오래 보는 날.',duration:'2시간 · 계획용',price:'성인 US$30 / 학생 US$17 · 자격 확인',tip:'월요일 10–17시, 수요일 휴관. 무료 아동은 12세 이하라 만 13세는 해당하지 않습니다. 학생 증빙 준비. 옥상은 현재 보수공사 폐쇄 안내 중입니다.',query:'The Metropolitan Museum of Art 1000 Fifth Avenue New York',source:'met'},
park:{name:'센트럴파크',kind:'park',desc:'미술관 관람 후 공원에서 점심과 휴식. 오래 걷기보다 벤치에 앉아 가을 분위기를 즐깁니다.',duration:'60–90분 · 계획용',price:'공원 무료 / 식사·자전거 별도',tip:'비가 오면 실내 점심으로 교체. 자전거는 필수가 아니며 보행 코스에 추가하지 말고 대체하세요.',query:'Central Park New York',source:null},
cards:{name:'Bleecker Trading · UWS',kind:'shop',desc:'포켓몬·스포츠 트레이딩카드와 수집품을 구경하는 아들을 위한 시간. 문구점이 아니라 카드 전문 매장입니다.',duration:'30–45분 · 계획용',price:'입장 구매 의무 없음 / 쇼핑 별도',tip:'공식 UWS 주소: 185 W 80th St. 월–토 10–20시, 일 10–19시. 살 금액을 먼저 정하고 방문하세요.',query:'Bleecker Trading 185 W 80th St New York',source:'cards'},
mj:{name:'브로드웨이 · MJ',kind:'theater',desc:'뉴욕에서의 공연 한 편. 월요일에 억지로 넣지 않고 금요일 저녁 후보로 두었습니다. 공항호텔 이동과 함께 계획해야 합니다.',duration:'공연·입장 대기 포함 저녁 블록',price:'10/9 공연·좌석 가격 미확인',tip:'10/9 회차 확보 후 뉴어크 호텔 늦은 체크인·교통을 확인하세요. 늦은 이동이 부담되면 MoMA 또는 휘트니를 줄이고 다른 공연일로 교체합니다.',query:'Neil Simon Theatre New York',source:'mj'},
falls:{name:'나이아가라 폭포',kind:'falls',desc:'버팔로에서 차를 빌려 캐나다 측 폭포로 이동합니다. 도착일에는 전망 산책을 우선하고, 명소 티켓은 실제 도착 시각에 맞춰 선택합니다.',duration:'도착 후 60–90분 · 계획용',price:'야외 전망 무료 / 주차·국경 통행료 별도',tip:'미국→캐나다 국경을 넘습니다. 렌터카 국경 통과 허용·보험·운전자 서류와 모자 입국 서류를 확인하세요. 도로 이동은 국경대기 포함 1.5–3시간 이상을 계획용 여유로 두되 실제 교통은 재확인합니다.',query:'Table Rock Welcome Centre Niagara Falls Ontario',source:'falls'},
journey:{name:'Journey Behind the Falls',kind:'falls',desc:'폭포 뒤 터널과 아래 전망대에서 물의 힘을 느끼는 유료 체험. 10/6 도착이 충분히 빠를 때만 선택합니다.',duration:'60–90분 · 대기 포함 추정',price:'13세 이상 CA$33 / 13% HST 별도',tip:'두 사람 모두 성인 구간입니다. 공식 페이지가 현재 주간 운영시간만 보여 10/6 운영 종료시각은 미확인. 10/7 출국 오전에 무리해서 넣지 마세요.',query:'Journey Behind the Falls Niagara Falls Canada',source:'falls'},
grand:{name:'그랜드센트럴',kind:'station',desc:'별자리가 그려진 천장 아래, 다음 도시로 떠나는 사람들을 구경합니다. 근처에서 식사하고 쉬어 가세요.',duration:'30–45분 · 계획용',price:'메인홀 관람 무료',tip:'10/7은 피곤하면 바로 휴식. 메인홀 관광은 10/8 점심 전후에도 가능합니다.',query:'Grand Central Terminal New York',source:null},
un:{name:'유엔본부 한국어 투어',kind:'un',desc:'10/8 10:00 사용자 예약 확정. 국제 외교가 이루어지는 공간을 가이드와 돌아봅니다. 회의 상황에 따라 방문 구역은 달라질 수 있습니다.',duration:'투어 약 1시간 + 사전 수속 1시간',price:'예약 완료 · 지불액 미공개',tip:'09:00까지 Visitor Check-in Office(801 1st Ave, 45th St) 도착 권장. 온라인 보안등록, 성인 실물 정부 발급 사진 신분증, 투어 확인서 준비. 아이는 성인 동반.',query:'United Nations Visitor Check In 801 1st Avenue New York',source:'un'},
nypl:{name:'뉴욕공립도서관 · 브라이언트파크',kind:'library',desc:'도서관 전시와 건축을 본 뒤 바로 뒤 공원에서 쉽니다. 유엔과 Summit 사이의 조용한 시간.',duration:'60–90분 · 계획용',price:'일반 방문 무료',tip:'목요일 본관 10–18시. Rose Main Reading Room의 일반 관광 시간은 월–토 10–11시로 유엔과 겹칩니다. 오후에 열람실 입장이 보장된다고 안내하지 않습니다.',query:'New York Public Library Stephen A Schwarzman Building',source:'nypl'},
summit:{name:'SUMMIT One Vanderbilt',kind:'tower',desc:'유리와 거울에 비친 뉴욕을 보는 여행의 대표 전망대. 10/8 오후로만 배치합니다.',duration:'90–120분 · 계획용',price:'일반 Experience US$44부터 / 주문당 온라인 수수료 US$3',tip:'15:30은 추천 슬롯이며 미예약입니다. 날짜·나이별 최종 가격과 재고 확인 필요. 반사 바닥을 고려해 바지·편한 신발을 준비하고 선글라스를 챙기세요.',query:'SUMMIT One Vanderbilt 45 E 42nd St New York',source:'summit'},
tram:{name:'루즈벨트섬 트램',kind:'tram',desc:'이스트리버 위를 건너는 짧은 공중 산책. 섬에 도착해 강변에서 사진을 찍고 돌아옵니다.',duration:'왕복·산책 60–90분 · 추정',price:'탑승일 운임 확인 필요',tip:'항공 이동이 있는 날이 아닌 10/9 오전 후보입니다. 운영 중단·기상과 교통 상황은 당일 확인하세요.',query:'Roosevelt Island Tramway Manhattan Station New York',source:null},
moma:{name:'MoMA',kind:'museum',desc:'현대미술의 대표 작품을 골라 보는 시간. 기존 10/6 오전에서 10/9로 이동해 공항 수속과 충돌하지 않게 했습니다.',duration:'90–120분 · 계획용',price:'성인 US$30 / 16세 이하 무료',tip:'금요일 10:30–20:30. 엄마는 일반권, 아들은 무료. 뉴욕주민 전용 금요일 무료 혜택은 관광객에게 적용되지 않습니다.',query:'Museum of Modern Art 11 West 53 Street New York',source:'moma'},
frontenac:{name:'샤토 프롱트낙 · 뒤프랭 테라스',kind:'castle',desc:'퀘벡의 지붕과 세인트로렌스강을 내려다보는 산책. 호텔 외관과 테라스가 기본 방문 범위입니다.',duration:'60–90분 · 계획용',price:'외관·테라스 산책 무료 / 내부 투어 별도',tip:'실제 숙박 호텔이므로 객실·사유 구역 출입은 별개입니다. 바람을 막는 겉옷을 준비하세요.',query:'Terrasse Dufferin Chateau Frontenac Quebec City',source:'quebec'},
petit:{name:'쁘띠샹플랭 · 로얄 광장',kind:'village',desc:'돌길과 작은 상점이 이어지는 구시가. 계단을 천천히 내려가거나 운영 중인 푸니큘라를 선택합니다.',duration:'90–120분 · 계획용',price:'거리 무료 / 푸니큘라·쇼핑 별도',tip:'오르내리는 경사가 있습니다. 이동 보조가 필요하면 푸니큘라 운영·운임을 먼저 확인하고, 비에는 미끄럼 주의.',query:'Quartier Petit Champlain Place Royale Quebec City',source:'quebec'},
citadel:{name:'성벽 · 시타델 주변',kind:'fort',desc:'퀘벡의 요새도시 풍경을 따라 걷습니다. 내부 가이드 투어는 예약·운영 확인 후 선택합니다.',duration:'45–60분 · 계획용',price:'주변 산책 / 내부 투어 별도 확인',tip:'10/11은 구시가 두 구역을 충분히 본 뒤 체력이 남을 때만. 성벽은 실제 출입 가능한 구간으로 이동하세요.',query:'La Citadelle de Quebec',source:'quebec'}
};
const DAYS=[
{date:'10/02',weekday:'금',city:'NEW YORK',scene:'ny',title:'늦은 도착, 충분한 휴식',note:'21:30 LGA 도착 · 사용자 확인. 관광 없이 숙소로 이동합니다. 한국 출발편과 캐나다 환승 상세는 항공권 원문 대조 필요.',stops:['airport'],events:[['21:30','LGA 도착','사용자 확인 · 입국 절차가 환승 공항에서 끝났는지는 항공권·운항편 확인.'],['도착 후','짐 수령 → 숙소 이동','이동·수령에 60–120분 이상 여유를 두는 계획용 추정. 늦은 체크인과 식사 가능 여부 확인.'],['늦은 밤','간단한 식사 · 취침','타임스퀘어와 Halal Guys는 다음 날로 미룹니다.']]},
{date:'10/03',weekday:'토',city:'LOWER MANHATTAN',scene:'ny',title:'항구에서 시작하는 뉴욕',note:'도착 다음 날입니다. 잠을 못 잤다면 섬 상륙 대신 다운타운 산책만 선택하세요. 페리 지연 시 월가 산책을 줄입니다.',stops:['statue','wall','memorial','time'],events:[['09:30 전후','다운타운 이동 · 아침','식사 후 Battery로. 지하철 이동 40–60분은 계획용 추정.'],['10:30–14:00','여신상 페리 · 점심','미예약 · 한 섬 중심. 엘리스섬 추가 시 월가 또는 메모리얼을 줄이세요.'],['14:30–15:30','월가 · 황소 · 소녀상','짧은 도보와 휴식.'],['16:00–17:00','9/11 야외 메모리얼','박물관은 별도 대안. 무거운 전시를 원치 않으면 야외만.'],['저녁','타임스퀘어 · Joe’s Pizza','숙소 쪽으로 복귀. 식당 지점·영업시간은 지도에서 재확인.']]},
{date:'10/04',weekday:'일',city:'BROOKLYN / WEST SIDE',scene:'ny',title:'강을 건너, 미술과 산책',note:'브루클린 → 웨스트사이드 두 블록. 그래피티 체험을 고르면 휘트니와 바꾸세요. 공연·헬기는 같은 오후에 추가하지 않습니다.',stops:['bridge','whitney','vessel'],events:[['09:00–11:00','브루클린 브리지 · 덤보','비·강풍이면 실내 일정으로 교체.'],['11:00–13:30','브루클린 점심 → 웨스트사이드','식사·휴식·이동 여유 포함. 교통 45–75분 계획용 추정.'],['13:30–15:00','휘트니 미술관','일요일 운영 확인 · 티켓 미예약.'],['15:00–17:00','하이라인 일부 · Vessel 외관','공원 전체 완주 없이 쉬엄쉬엄. 내부 입장은 선택.'],['저녁','식사 후 휴식','헬기·버스는 별도 대체 옵션에서 선택하세요.']]},
{date:'10/05',weekday:'월',city:'UPPER MANHATTAN',scene:'ny',title:'작품 한 점, 공원 한 바퀴',note:'MET → 공원 → 카드숍. MET 옥상은 현재 폐쇄 안내 중이므로 기본 코스에서 제외했습니다.',stops:['met','park','cards','time'],events:[['아침','Ess-a-Bagel 또는 근처 아침','희망 식당. 선택 지점에 따라 동선이 달라지므로 멀리 돌아가지 않습니다.'],['10:00–12:00','MET 핵심 전시','학생 증빙 확인. 예약 완료 아님.'],['12:00–14:00','공원 근처 점심 · 센트럴파크','비가 오면 실내 식사·휴식.'],['14:30–15:15','Bleecker Trading UWS','185 W 80th St · 카드·수집품 매장.'],['늦은 오후','숙소 휴식 · Halal Guys 저녁','희망 식당 W 53rd / 6th Ave 주변 지점·영업 확인. 다음 날 공항 이동 준비.']]},
{date:'10/06',weekday:'화',city:'BUFFALO / NIAGARA',scene:'niagara',title:'빌딩 숲에서 물의 도시로',note:'13:29 JFK 출발 · 사용자 확인. MoMA를 넣지 않습니다. 버팔로 도착 시각이 미확인이라 나이아가라 체험은 조건부입니다.',stops:['airport','falls','journey'],events:[['08:30 전후','체크아웃 · JFK 이동','10:30 전후 공항 도착을 목표로 한 보수적 계획. 당일 교통·항공사 수속 마감 재확인.'],['13:29','JFK → 버팔로','사용자 확인 · 도착시각 원문 확인 필요.'],['도착 후','허츠 렌터카 → 국경 → 나이아가라','국경 통과 허용·보험·서류·호텔 주차 확인. 국경 대기는 예측 보장 불가.'],['체크인 후','폭포 산책 · 저녁','Journey Behind the Falls는 일찍 도착하고 운영시간이 맞을 때만. 야간 조명·불꽃은 당일 운영 확인.']]},
{date:'10/07',weekday:'수',city:'NIAGARA / NEW YORK',scene:'niagara',title:'돌아가는 날에는 여유를',note:'사용자 제공: 13:53 버팔로 출발 · 17:30 JFK 도착. 두 공항은 같은 시간대이므로 중간 경유·항공편 변경 여부를 예약 원문으로 재확인하세요. 시각은 임의 수정하지 않았습니다.',stops:['falls','airport','grand'],events:[['08:00 전후','아침 · 체크아웃','폭포 유료 관광을 추가하지 않습니다.'],['09:00 전후','국경 통과 → 주유·렌터카 반납','11:00 전후 공항 도착 목표의 계획용 여유. 국경 혼잡 시 더 일찍 출발.'],['13:53 → 17:30','버팔로 → JFK','사용자 제공 · 상세 구간 대조 필요.'],['도착 후','호텔 이동 · 저녁 · 휴식','도심 이동 60–120분 이상 계획용 추정. Edge 제외, 그랜드센트럴은 체력이 남을 때만.']]},
{date:'10/08',weekday:'목',city:'MIDTOWN EAST',scene:'ny',title:'세계의 회의장, 하늘의 전망대',note:'유엔 10:00 확정 · Summit 오후만. 유엔 공식 권장에 따라 09:00 방문자 체크인 도착. 기존 안내서의 09:20–09:30 숙소 출발안은 사용하지 않습니다.',stops:['un','grand','nypl','summit'],events:[['09:00','유엔 방문자 체크인','온라인 보안등록·실물 신분증·투어 확인서 준비.'],['10:00–11:00 전후','유엔 한국어 투어','사용자 예약 확정 · 방문 구역은 회의 상황에 따라 달라짐.'],['11:30–13:00','그랜드센트럴 · 점심','수속 지연에 대비해 점심 시각 유연하게.'],['13:00–14:30','NYPL · 브라이언트파크','오후 Rose 열람실 일반관광 입장은 보장되지 않음. 전시·건축·공원 중심.'],['15:30–17:30','Summit One Vanderbilt','추천 슬롯 · 미예약. 10/8 오후 범위 안에서 실제 재고 선택.']]},
{date:'10/09',weekday:'금',city:'MANHATTAN / NEWARK',scene:'ny',title:'마지막 뉴욕, 좋아하는 것 하나',note:'기본안은 트램·MoMA 후 공항호텔 이동. MJ를 원하면 저녁 공연 확보 → 뉴어크 늦은 체크인을 확인하는 대체안으로 바꿉니다.',stops:['tram','moma','mj','airport'],events:[['오전','체크아웃 · 짐 보관 확인','숙소 보관 가능 여부부터 확인.'],['09:00–10:30','루즈벨트섬 트램','선택 · 피곤하면 생략하고 MoMA만.'],['11:00–13:00','MoMA','10/6에서 이동. 16세 이하 무료 확인.'],['13:00–15:00','점심 · 짐 찾기','뉴어크 이동 또는 공연 대체안 선택.'],['오후','뉴어크 공항호텔 이동','기본안 · 60–120분 이상 계획용 여유. 호텔 공항 셔틀 운행 확인.'],['저녁 · 대체안','MJ 공연','회차·좌석 미확인. 공연 선택 시 뉴어크 늦은 체크인·심야 교통을 먼저 확인.']]},
{date:'10/10',weekday:'토',city:'QUÉBEC CITY',scene:'quebec',title:'Bonjour, 작은 프랑스',note:'10:12 뉴어크 출발 → 12:02 퀘벡 도착 · 사용자 확인. 숙소의 정확한 불문명은 미확인. 도착일은 구시가 상부 산책만.',stops:['airport','frontenac'],events:[['07:00 전후','공항 이동·국제선 수속','출발 3시간 전 도착을 목표로 호텔 셔틀·수속 마감 재확인.'],['10:12 → 12:02','뉴어크 → 퀘벡','사용자 확인.'],['12:02–15:00','입국 · 이동 · 점심 · 체크인','도심 교통·수속 시간은 미확인, 여유 블록으로 배치.'],['15:30 이후','구시가 · 프롱트낙 외관 · 저녁','바람이 차면 카페로. 무리한 외곽 관광 없음.']]},
{date:'10/11',weekday:'일',city:'OLD QUÉBEC',scene:'quebec',title:'돌길을 따라 걷는 하루',note:'구시가 상부와 하부를 나눠 천천히. 시타델은 체력·운영에 따른 선택. 단풍과 날씨는 보장하지 않습니다.',stops:['frontenac','petit','citadel'],events:[['09:30–11:00','프롱트낙 · 뒤프랭 테라스','외관과 강 전망.'],['11:00–13:30','쁘띠샹플랭 · 로얄 광장 · 점심','계단 또는 푸니큘라 선택. 운행·요금은 당일 확인.'],['13:30–15:00','카페 · 자유시간','사진·기념품, 발 쉬는 시간.'],['15:00–16:00','성벽·시타델 주변 선택 산책','내부 투어 미예약. 피곤하면 생략.'],['저녁','이른 식사 · 귀국 준비','내일 공항 이동과 수하물 연결 확인.']]},
{date:'10/12',weekday:'월',city:'QUÉBEC / MONTRÉAL',scene:'quebec',title:'여행을 접어, 집으로',note:'10:25 퀘벡 출발 → 몬트리올 → 도쿄. 몬트리올은 관광이 아닌 환승입니다. 연결편 출발시각·게이트는 항공권 확인 필요.',stops:['airport'],events:[['07:30 전후','공항 도착 목표','호텔 출발은 실제 교통·수속 기준으로 조정.'],['10:25','퀘벡 → 몬트리올','사용자 확인 · 이후 도쿄행 연결.'],['환승','몬트리올 공항 내 이동','공항 밖 관광 없음. 연결편 시각·수하물 목적지 확인.'],['기내','도쿄로 이동 · 휴식','날짜 변경: 도착은 현지 10/13.']]},
{date:'10/13',weekday:'화',city:'TOKYO / INCHEON',scene:'quebec',title:'집에 도착하는 마지막 장면',note:'15:25 나리타 도착 → 19:00 출발 → 21:30 인천 T2 도착 · 사용자 확인. 한 장의 연결 항공권이어도 수하물 최종 목적지·터미널·탑승권을 확인하세요.',stops:['airport'],events:[['15:25','나리타 도착','공항 내 환승 경로·터미널 확인.'],['19:00','나리타 → 인천','기내 반입 수하물과 다음 탑승권 확인.'],['21:30','인천공항 터미널 2 도착','수하물 찾기 · 귀가. 마지막 날은 한국 시간입니다.']]}
];
const ALTERNATIVES=[['그래피티 체험','10/4 휘트니를 대체','브루클린에서 체험 장소·시간·13세 참가 조건을 먼저 확인. 덤보와 Bushwick은 같은 동네가 아니므로 이동 여유 필요. 업체 미선정·미예약.'],['문 없는 헬기','10/4 오후 블록 전체를 대체','연령만으로 참가 가능을 확정하지 않습니다. 신장·체중·하네스·보호자·이착륙장·날씨·취소 정책을 운영사에 확인. 기존 가격은 재사용하지 않음.'],['TopView 또는 Big Bus','걷는 일정 한 블록과 교체','두 상품을 모두 사지 않습니다. 노선·정류장·13세 요금·탑승시간을 비교 후 선택. 고정 투어로 향하는 정시 이동수단으로 사용하지 않음.'],['Edge','Vessel 주변 산책 일부와 교체','Summit이 대표 전망대이므로 중복 지출은 선택. 10/7 귀환일 저녁에는 넣지 않음.'],['9/11 박물관','10/3 월가·저녁 일부를 줄이기','야외 메모리얼과 입장이 다릅니다. 최소 90분 이상 확보. 실제 티켓 가격·슬롯을 확인한 뒤 페리와 간격을 확보.'],['MJ 공연','10/9 저녁 대안','공연 회차 미확인. 늦은 뉴어크 이동이 부담되면 10/4 오후 일정을 비우고 공연 가능 회차로 대체. 어느 회차도 예약 완료로 표시하지 않음.']];
const CHECKS=[['고정된 것','항공·숙박 순서, 유엔 10/8 10:00은 사용자 확인. 정확한 숙소명·항공편 번호·예약 원문은 공개본에서 제외했습니다.'],['아직 예약하지 않은 것','Summit 10/8 오후, 여신상, MJ, 미술관, 체험은 미예약. 왕관의 현재 매진 여부와 가격·슬롯은 재확인 필요.'],['국경·렌터카','허츠 버팔로 지점의 캐나다 운행 허용·보험·반납 위치, 운전면허·국제운전면허 필요 서류를 확인. 미국 재입국 자격과 캐나다 항공 입국 자격은 여권 국적별 확인.'],['엄마와 아이의 캐나다 입국','캐나다 정부는 한 부모 동반 시 아이 여권·출생증명 사본·비동반 부모의 영문/불문 동의서 및 서명된 여권/신분증 사본 준비를 안내합니다. 양육권 등 개별 상황에 맞는 서류 확인.'],['아직 대조할 이동 정보','10/6 버팔로 도착시각, 10/7 13:53→17:30 구간, 10/2 캐나다 환승편, 귀국 몬트리올 연결시각, 퀘벡 숙소 정확한 이름. 임의로 확정하지 않았습니다.'],['비·피로 대안','브리지·공원은 짧게, MoMA·NYPL 등 실내로 교체. 매일 식사와 휴식 확보. 보행 한도·예산은 미제공이므로 중간 강도 초안입니다.']];
