import {META,STOPS,SOURCES,WEATHER} from './data.js';
const $=s=>document.querySelector(s),maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
let selected=0,mode='day',photo=false,touring=false,paused=false,tourClock=0,failed=false,flat=false,flight=null,T,renderer,scene,camera,controls,coast,sun,ambient,labels=[];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,errors=[];
addEventListener('error',e=>errors.push(e.message));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
function scheduleHTML(){return STOPS.map(s=>`<section class="schedule"><time>${s.time} — ${s.end}</time><h3>${s.name}</h3><p>${s.desc}</p><p>${s.tip}</p></section>`).join('');}
function fillGuide(){const sourceHTML=SOURCES.map(([n,u,note])=>`<li><a href="${u}" target="_blank" rel="noopener noreferrer">${n} ↗</a><p>${note}</p></li>`).join('');$('#guideBody').innerHTML=`<p class="warning"><b>9월 12일 전용 계획입니다.</b> 실시간 안내가 아닙니다. 다른 날짜에는 통행시간·날씨를 다시 확인해야 합니다. 모든 시각은 한국시간(KST)입니다.</p><h3>오늘의 바닷길</h3><p><b>07:07–15:51 / 19:15–다음 날 04:06</b><br>화성도시공사 공식 예정표를 확인했습니다. 기상에 따라 약 30분 편차가 발생할 수 있습니다. 실제 차단기·관리자 안내를 따르세요. 19:30 진입도 보장하지 않습니다.</p><p>제부도관리사무소 <a href="tel:0313553924">031-355-3924</a> · <a href="${SOURCES[0][1]}" target="_blank" rel="noopener noreferrer">출발 전 공식 통행표 ↗</a></p><h3>날씨 · 보조 자료</h3><div class="weather">${WEATHER.map(([t,w,c,v])=>`<div>${t} · ${w}<b>${c}</b>${v}</div>`).join('')}</div><p><small>바다타임 2026-09-12 안산탄도 표시 예보, 확인 ${META.checked}. 기상청 단기예보 페이지는 제작 시 접근 실패하여 직접 대조하지 못했습니다. 강수확률 20%는 재확인되지 않아 기재하지 않습니다. 최신 특보·바람은 출발 전 재확인하세요.</small></p><h3>오늘의 흐름</h3><p>13:00 분당 출발. 도착·이동 시각은 교통을 실측한 값이 아닌 계획용 예상입니다. 일몰 18:46과 공식 통행 예정 시각만 별도 출처로 확인했습니다.</p>${scheduleHTML()}<h3>플랜 B · 섬에 못 들어가도 좋은 하루</h3><p>개방 지연, 비·강풍, 피로, 교통 정체가 있으면 제부도를 생략하고 전곡항에서 저녁 후 귀가합니다. 카페·식당·체험은 예약하지 않았고 영업·마지막 주문·요금은 현장에서 확인합니다.</p><h3>차량과 사진</h3><p>사이버트럭도 일반 차량과 동일하게 통제를 따릅니다. 바닷길에서 정차·주차·촬영하지 않고 침수 구간에는 진입하지 않습니다. 주차는 표시된 주차면만 이용합니다. 높이·폭·회전 공간 제한은 현장 확인이 필요합니다. 누에섬 도보 왕복은 기본 일정에서 제외했습니다.</p><h3>지도 아닌 미니어처</h3><p>해안·풍차·요트·차량은 자체 제작한 개념 모형입니다. 축척·방향·도로·건물 위치가 실제와 다릅니다. 낮·노을·밤은 연출이며 실시간 조수·날씨 시뮬레이션이 아닙니다. 실제 이동은 각 장소의 지도 링크를 사용하세요.</p><h3>출처와 확인 시점</h3><p>${META.checked}</p><ul>${sourceHTML}</ul><p><small>공개 링크이며 noindex는 접근제어가 아닙니다. 상세 출발 주소·이름·예약정보는 넣지 않았습니다. 새로운 API 가입, 유료 이미지·음악 생성, 자동 예약은 없습니다. 3D 엔진: <a href="vendor/LICENSE-three.txt">Three.js / MIT License</a>. 장소·일정 정보는 JavaScript로 동작하며 WebGL 미지원 때도 남습니다.</small></p>`;
 $('#printAll').innerHTML=`<h1>${META.title}</h1><p>2026.09.12 토요일 · 13:00 분당 출발 · 한국시간</p><p>공식 통행 예정 07:07–15:51 / 19:15–익일 04:06. 약 30분 편차 가능, 현장 통제가 우선입니다. 바닷길 정차·침수 진입 금지.</p>${scheduleHTML()}<h2>대체 동선</h2><p>개방 지연·악천후·피로 시 전곡항 저녁 후 귀가. 모든 이동 시각은 계획용 예상, 카페·식당은 미예약입니다.</p><h2>확인 자료 · ${META.checked}</h2><ul>${sourceHTML}</ul>`;
 $('#timeline').innerHTML=STOPS.map((s,i)=>`<button data-stop="${i}" aria-pressed="${i===0}"><span class="number">0${i+1}</span><time>${s.time}</time><b>${s.short}</b></button>`).join('');}
function panel(){const s=STOPS[selected];$('#stepno').textContent=`0${selected+1} / 06`;$('#counter').textContent=`${selected+1} / ${STOPS.length}`;$('#previous').disabled=selected===0;$('#next').disabled=selected===STOPS.length-1;$('#panelBody').innerHTML=`<p class="eyebrow">${s.tag}</p><span class="time">${s.time} — ${s.end}</span><h2>${s.name}</h2><p class="desc">${s.desc}</p>${photo?`<h3>오늘의 촬영 팁</h3><p>${s.photo}</p>`:`<p class="note">${s.tip}</p><h3>알아두면 좋은 것</h3><p>${s.detail}</p>`}<a class="map" href="${maps(s.query)}" target="_blank" rel="noopener noreferrer">${selected===1?'카페 후보 · ':''}실제 지도에서 보기 ↗</a>`;$('#panelBody').scrollTop=0;$('#announce').textContent=`${s.time} ${s.name}`;document.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.stop)===selected));labels.forEach(l=>l.el.classList.toggle('active',l.id===s.place));$('#tourLabel').textContent=`${touring?'자동 투어 · ':''}${s.short}`;}
function setMode(m){mode=m;document.body.classList.toggle('night',m==='night');document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===m));if(!scene)return;scene.background.set(m==='day'?'#dce9e2':m==='sunset'?'#e7cbb0':'#273f4b');coast.setMode(m);sun.color.set(m==='day'?'#fff4d7':m==='sunset'?'#ffd09a':'#b2d0e4');sun.intensity=m==='night'?.85:2.2;sun.position.set(m==='sunset'?-650:-400,m==='sunset'?200:700,350);ambient.intensity=m==='night'?.85:2;}
function select(i,manual=true){selected=Math.max(0,Math.min(STOPS.length-1,i));if(manual&&touring){paused=true;$('#pause').textContent='계속';}panel();setMode(STOPS[selected].mode);focus();$(`[data-stop="${selected}"]`).scrollIntoView({inline:'nearest',block:'nearest',behavior:'instant'});}
function fly(target,zoom){if(!camera)return;const offset=flat?new T.Vector3(0,1000,.1):new T.Vector3(630,740,950);flight={t:performance.now(),a:camera.position.clone(),b:target.clone().add(offset),ta:controls.target.clone(),tb:target,za:camera.zoom,zb:zoom};if(reduced){camera.position.copy(flight.b);controls.target.copy(target);camera.zoom=zoom;camera.updateProjectionMatrix();flight=null;}}
function focus(){if(!camera)return;const [x,z]=STOPS[selected].camera;fly(new T.Vector3(x,15,z),innerWidth<701?.8:1.6);}
function overview(){fly(new T.Vector3(20,0,0),innerWidth<701?.48:.8);}
function fallback(){failed=true;$('#fallback').hidden=false;$('#labels').hidden=true;$('#loading').hidden=true;if(renderer)renderer.domElement.hidden=true;document.querySelectorAll('#zoomIn,#zoomOut,#flat,#overview').forEach(b=>b.disabled=true);}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight;camera.left=-390*aspect;camera.right=390*aspect;camera.top=390;camera.bottom=-390;camera.setViewOffset(innerWidth,innerHeight,innerWidth<701?0:innerWidth*.035,innerWidth<701?innerHeight*.085:-innerHeight*.02,innerWidth,innerHeight);camera.updateProjectionMatrix();}
async function init3D(){try{T=await import('three');const [{OrbitControls},{createCoast,LOCATIONS,NAMES}]=await Promise.all([import('./vendor/OrbitControls.js'),import('./coast.js')]);if(new URLSearchParams(location.search).has('flat'))throw Error('2D requested');renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;$('#world').prepend(renderer.domElement);scene=new T.Scene();scene.background=new T.Color('#dce9e2');camera=new T.OrthographicCamera(-600,600,390,-390,1,5000);camera.position.set(650,740,950);camera.zoom=innerWidth<701?.48:.8;controls=new OrbitControls(camera,renderer.domElement);controls.target.set(20,0,0);controls.enableDamping=true;controls.dampingFactor=.06;controls.minZoom=.3;controls.maxZoom=3;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.05;controls.addEventListener('start',()=>{flight=null;if(touring){paused=true;$('#pause').textContent='계속';}});ambient=new T.HemisphereLight('#fff6e5','#7e9b85',2);scene.add(ambient);sun=new T.DirectionalLight('#fff4d7',2.2);sun.position.set(-400,700,350);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-850,right:850,top:850,bottom:-850,near:1,far:1900});sun.shadow.normalBias=1.5;scene.add(sun);coast=createCoast();scene.add(coast.root);for(const [id,[x,z]] of Object.entries(LOCATIONS)){const el=document.createElement('button');el.className='landmark';el.textContent=NAMES[id];el.setAttribute('aria-label',NAMES[id]+' 안내');el.onclick=()=>{if(id==='nue'){$('#guide').showModal();$('#guideBody').scrollTop=0;}else select(STOPS.findIndex(s=>s.place===id));};$('#labels').append(el);labels.push({id,el,point:new T.Vector3(x,id==='nue'?100:55,z)});}renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback();});resize();controls.update();setMode(mode);$('#loading').hidden=true;panel();}catch(e){fallback();if(!String(e).includes('2D requested'))console.warn('3D unavailable, using accessible 2D guide:',e);}}
let last=0,elapsed=0;
function coveredLabel(x,y){const regions=['header.title','.status','.toptools','.sceneControls','footer',...document.body.classList.contains('panelClosed')?[]:['#panel']];return regions.some(s=>{const r=$(s).getBoundingClientRect();return x+85>r.left&&x-85<r.right&&y>r.top&&y-30<r.bottom;});}
function frame(t){requestAnimationFrame(frame);const dt=Math.min((t-last)/1000,1);last=t;if(document.hidden)return;if(!reduced)elapsed+=Math.min(dt,.08);if(renderer&&!failed){coast.animate(elapsed);if(flight){const p=Math.min(1,(t-flight.t)/1100),e=p*p*(3-2*p);camera.position.lerpVectors(flight.a,flight.b,e);controls.target.lerpVectors(flight.ta,flight.tb,e);camera.zoom=T.MathUtils.lerp(flight.za,flight.zb,e);camera.updateProjectionMatrix();if(p===1)flight=null;}controls.update();renderer.render(scene,camera);labels.forEach(l=>{const p=l.point.clone().project(camera),x=(p.x+1)*innerWidth/2,y=(1-p.y)*innerHeight/2;l.el.style.transform=`translate(-50%,-100%) translate(${x}px,${y}px)`;l.el.hidden=p.z>1||x<0||x>innerWidth||y<0||y>innerHeight||coveredLabel(x,y);});}if(touring&&!paused){tourClock+=dt;$('#progress').value=tourClock/9;if(tourClock>=9){tourClock=0;if(selected===STOPS.length-1)stopTour();else select(selected+1,false);}}}
function stopTour(){touring=false;paused=false;tourClock=0;$('#tourbar').hidden=true;$('#tour').textContent='▷ 자동 투어';}
function togglePanel(){const closed=document.body.classList.toggle('panelClosed');$('#panelToggle').textContent=closed?'정보 보기':'정보 접기';$('#panelToggle').setAttribute('aria-expanded',!closed);}
fillGuide();panel();
document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>select(Number(b.dataset.stop)));
document.querySelectorAll('[data-stop]').forEach(b=>b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click();}}));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#previous').onclick=()=>select(selected-1);$('#next').onclick=()=>select(selected+1);$('#photoMode').onclick=()=>{photo=!photo;$('#photoMode').setAttribute('aria-pressed',photo);panel();};$('#panelToggle').onclick=togglePanel;$('#guideOpen').onclick=()=>$('#guide').showModal();$('#guideClose').onclick=()=>$('#guide').close();$('#print').onclick=()=>{$('#guide').close();window.print();};$('#home').onclick=e=>{e.preventDefault();overview();};$('#overview').onclick=overview;
$('#zoomIn').onclick=()=>{if(camera){flight=null;camera.zoom=Math.min(3,camera.zoom*1.2);camera.updateProjectionMatrix();}};$('#zoomOut').onclick=()=>{if(camera){flight=null;camera.zoom=Math.max(.3,camera.zoom/1.2);camera.updateProjectionMatrix();}};$('#flat').onclick=()=>{flat=!flat;$('#flat').setAttribute('aria-pressed',flat);$('#flat').textContent=flat?'입체 보기':'위에서';focus();};
$('#tour').onclick=()=>{if(touring)return stopTour();touring=true;paused=false;tourClock=0;if(selected===STOPS.length-1)select(0,false);$('#tourbar').hidden=false;$('#tour').textContent='■ 투어 종료';$('#pause').textContent='일시정지';panel();focus();};$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'계속':'일시정지';};$('#stop').onclick=stopTour;
addEventListener('resize',resize);await init3D();requestAnimationFrame(frame);
window.travelDiagnostics=()=>({selected,mode,touring,paused,flat,webgl:!failed,flight:!!flight,zoom:camera?.zoom,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,errors,stops:STOPS.length,labels:labels.length});
