const $=s=>document.querySelector(s);
const RESTAURANTS=[
{name:'선창횟집',area:'제부도 · 섬에 들어갔을 때',tag:'20시 저녁 후보',why:'조개구이와 칼국수로 바다 여행을 마무리하고 싶을 때. 개방이 늦으면 본토 대안을 선택하세요.',menu:'조개구이 기본세트 · 왕새우 · 바지락칼국수',price:'조개구이 2인 50,000원 — 2026.02 방문기 기준, 현재 가격·구성 재확인',hours:'토요일 11:00–22:30 (다이닝코드 표시). Google에는 23:00 마감으로 표시돼 차이가 있습니다. 마지막 주문은 미확인.',parking:'무료주차 표기 및 건물 뒤 주차장 방문기 확인. 사이버트럭 진입 폭·빈자리 미확인.',address:'화성시 서신면 해안길 282-1',phone:'031-357-2520',sources:[['업체정보·메뉴','https://www.diningcode.com/profile.php?rid=sen5tiNmoPcA'],['2026.02 가격·주차 방문기','https://blackforest.tistory.com/1254']]},
{name:'해금강횟집 전곡항',area:'전곡항 · 본토 대안',tag:'개방 지연 시 추천',why:'섬 진입을 기다리지 않고 저녁을 먹는 대안입니다. 회·탕류뿐 아니라 물회와 회덮밥 등 식사류 후보도 있습니다.',menu:'모듬회 · 생우럭매운탕 · 연포탕 / 물회·회덮밥',price:'메뉴 표기: 모듬회 소 130,000원 · 우럭매운탕 소 60,000원. 최근 수록 후기: 물회 20,000원·회덮밥 15,000원(주문 전 재확인)',hours:'토요일 05:00–24:00 (다이닝코드 표시). 마지막 주문·당일 재료 소진은 미확인.',parking:'방문기에 상가 옆 및 인근 공영주차장 안내. 당일 요금·주차 여유·대형차 적합성 미확인.',address:'화성시 서신면 전곡항로14번길 1-24',phone:'0507-1328-3307',sources:[['메뉴·영업·주차 후기','https://www.diningcode.com/profile.php?rid=RE9xADgDYTak']]},
{name:'탄도칼국수',area:'탄도항 · 낮 또는 이른 식사',tag:'영업 확인 후 방문',why:'탄도항 일정 중 국수·파전으로 간단히 식사하고 싶을 때의 가까운 후보입니다. 늦은 저녁 대안으로 확정하지 않았습니다.',menu:'바지락칼국수 · 해물칼국수 · 건강해물파전',price:'2025.11 방문기: 바지락칼국수 1인 10,000원 · 해물칼국수 18,000원 · 파전 18,000원. 과거 가격으로 현재 재확인 필요.',hours:'토요일 정확한 마감·마지막 주문 미확인. 영업시간이 유동적이라는 방문 기록이 있어 현장 확인 후 선택.',parking:'2025.11 방문기에 가게 뒤 주차공간 안내. 현재 이용 조건·진입 폭 미확인.',address:'안산시 단원구 대부황금로 17-34 1층',phone:null,sources:[['주소·가격·주차 방문기','https://m.blog.naver.com/sarah_1227_/224057450008']]}
];
const cards=()=>RESTAURANTS.map((r,i)=>`<section class="foodcard"><span class="foodtag">${r.tag}</span><p class="edition">${r.area}</p><h3>${r.name}</h3><p>${r.why}</p><dl><dt>대표 메뉴</dt><dd>${r.menu}</dd><dt>가격 참고</dt><dd>${r.price}</dd><dt>영업·주문 마감</dt><dd>${r.hours}</dd><dt>주차</dt><dd>${r.parking}</dd><dt>주소</dt><dd>${r.address}</dd></dl><div class="foodlinks"><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.name+' '+r.address)}" target="_blank" rel="noopener noreferrer">실제 지도 ↗</a>${r.phone?`<a href="tel:${r.phone.replaceAll('-','')}">전화 확인</a>`:''}${r.sources.map(([t,u])=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a>`).join('')}</div></section>`).join('');
$('#foodBody').innerHTML=`<p class="warning">동선과 공개 메뉴 정보를 기준으로 고른 <b>식사 후보</b>입니다. 직접 시식·당일 영업 확인·예약은 하지 않았습니다. 업체 공식 공지는 확보하지 못해 지도형 업체정보와 방문기를 교차 참고했습니다. 확인: 2026.09.12 12:15 KST.</p><p><b>섬에 들어가면 선창횟집 → 진입이 늦으면 해금강횟집.</b> 조개구이는 준비·식사에 시간이 걸려 20시 방문 시 21시 귀가 출발이 늦어질 수 있습니다. 출도 상태와 마지막 주문을 먼저 확인하세요.</p>${cards()}<p><small>리뷰·블로그 정보는 최신 영업 보장이 아닙니다. 가격은 메뉴/세트 기준이며 인당 총예산이 아닙니다. 안전하게 주차한 뒤 전화하세요. 조개류는 충분히 익혀 드세요.</small></p>`;
$('#foodOpen').onclick=()=>$('#food').showModal();$('#foodClose').onclick=()=>$('#food').close();
function attach(){const p=$('#panelBody');if(p&&!p.querySelector('.foodPanelLink')){const b=document.createElement('button');b.className='foodPanelLink';b.textContent='이 동선의 추천 맛집 3곳 →';b.onclick=()=>$('#food').showModal();p.append(b);}const print=$('#printAll');if(print?.children.length&&!print.querySelector('.foodPrint')){const section=document.createElement('section');section.className='foodPrint';section.innerHTML='<h2>식사 후보 · 2026.09.12 확인</h2><p>당일 영업·마지막 주문 미확인, 전화·예약 미실시. 제부도 진입 지연 시 본토 식사로 변경합니다.</p>'+cards();print.append(section);}}
new MutationObserver(attach).observe($('#panelBody'),{childList:true});attach();
// Original browser-synthesized ambient score. No downloaded songs or paid media.
let ctx,master,analyser,playing=false,manualOff=false,busy=false,timer,beat=0,next=0,scheduled=0,volume=.3;
const toggle=$('#musicToggle'),slider=$('#musicVolume');
function ui(){toggle.textContent=playing?'♫ 음악 끄기':'♫ 음악 켜기';toggle.setAttribute('aria-pressed',playing);$('#volumeValue').textContent=Math.round(volume*100)+'%';}
function note(midi,t,d,g=.1){const o=ctx.createOscillator(),v=ctx.createGain();o.type='sine';o.frequency.value=440*Math.pow(2,(midi-69)/12);v.gain.setValueAtTime(0,t);v.gain.linearRampToValueAtTime(g,t+.025);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(master);o.start(t);o.stop(t+d+.05);o.onended=()=>{o.disconnect();v.disconnect();};scheduled++;}
function schedule(){if(!playing)return;const chords=[[48,55,60,64],[45,52,57,60],[41,48,53,57],[43,50,55,59]],melody=[72,76,79,76,74,72,67,71];while(next<ctx.currentTime+1.5){const bar=Math.floor(beat/8)%4;if(beat%8===0)chords[bar].forEach(m=>note(m,next,4,.065));note(melody[beat%8]+(bar===2?-2:0),next,1.7,.085);next+=.6;beat++;}}
async function start(){if(playing||busy||document.hidden)return;busy=true;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('Web Audio unsupported');if(!ctx){ctx=new Audio();master=ctx.createGain();analyser=ctx.createAnalyser();analyser.fftSize=256;master.connect(analyser);analyser.connect(ctx.destination);}await ctx.resume();if(ctx.state!=='running')throw Error('Audio blocked');playing=true;master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setValueAtTime(volume,ctx.currentTime);next=ctx.currentTime+.05;schedule();clearInterval(timer);timer=setInterval(schedule,300);ui();}catch(e){toggle.textContent='♫ 눌러서 재시도';toggle.title=String(e);}finally{busy=false;}}
function stop(manual=true){manualOff=manual;playing=false;clearInterval(timer);if(ctx){master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setValueAtTime(0,ctx.currentTime);ctx.suspend();}ui();}
toggle.onclick=()=>{if(playing)stop(true);else{manualOff=false;start();}};
slider.oninput=()=>{volume=Number(slider.value)/100;if(master&&playing)master.gain.setTargetAtTime(volume,ctx.currentTime,.03);ui();};
function firstGesture(e){if(e.target.closest('#musicToggle,#musicVolume')||manualOff||playing)return;start();}
document.addEventListener('pointerdown',firstGesture);document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key))firstGesture(e);});
document.addEventListener('visibilitychange',()=>{if(!ctx)return;if(document.hidden){clearInterval(timer);ctx.suspend();}else if(playing){ctx.resume().then(()=>{next=ctx.currentTime+.05;schedule();clearInterval(timer);timer=setInterval(schedule,300);}).catch(()=>{playing=false;ui();});}});
window.musicDiagnostics=()=>{let peak=0;if(analyser&&playing){const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);peak=Math.max(...data.map(Math.abs));}return{playing,manualOff,state:ctx?.state||'not-started',volume,scheduled,peak};};
window.foodDiagnostics=()=>({restaurants:RESTAURANTS.length,cards:$('#foodBody').querySelectorAll('.foodcard').length});
ui();
