import {META,STOPS,SOURCES,WEATHER} from './data.js?v=0913-1';
import {guideHTML,printHTML} from './guide.js?v=0913-1';
const $=s=>document.querySelector(s),maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
let selected=0,mode='day',photo=false,touring=false,paused=false,tourClock=0,failed=false,flat=false,flight=null,T,renderer,scene,camera,controls,coast,sun,ambient,labels=[];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,errors=[];
addEventListener('error',e=>errors.push(e.message));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
function scheduleHTML(){return STOPS.map(s=>`<section class="schedule"><time>${s.time} — ${s.end}</time><h3>${s.name}</h3><p>${s.desc}</p><p>${s.tip}</p></section>`).join('');}
function fillGuide(){
 $('#guideBody').innerHTML=guideHTML(); $('#printAll').innerHTML=printHTML();
 $('#timeline').innerHTML=STOPS.map((s,i)=>`<button data-stop="${i}" aria-pressed="${i===0}"><span class="number">0${i+1}</span><time>${s.time}</time><b>${s.short}</b></button>`).join('');
}
function panel(){const s=STOPS[selected];$('#stepno').textContent=`0${selected+1} / 06`;$('#counter').textContent=`${selected+1} / ${STOPS.length}`;$('#previous').disabled=selected===0;$('#next').disabled=selected===STOPS.length-1;$('#panelBody').innerHTML=`<p class="eyebrow">${s.tag}</p><span class="time">${s.time} — ${s.end}</span><h2>${s.name}</h2><p class="desc">${s.desc}</p>${photo?`<h3>오늘의 촬영 팁</h3><p>${s.photo}</p><p class="note">재배포 권리가 확인된 현장 사진은 미확보입니다. 가짜 사진 대신 아래 지도·원문에서 실제 사진을 확인하세요.</p>`:`<p class="note">${s.tip}</p><h3>알아두면 좋은 것</h3><p>${s.detail}</p>`}<a class="map" href="${maps(s.query)}" target="_blank" rel="noopener noreferrer">실제 지도·현장 사진 보기 ↗</a>`;$('#panelBody').scrollTop=0;$('#announce').textContent=`${s.time} ${s.name}`;document.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.stop)===selected));labels.forEach(l=>l.el.classList.toggle('active',l.id===s.place));$('#tourLabel').textContent=`${touring?'자동 투어 · ':''}${s.short}`;}
function setMode(m){mode=m;document.body.classList.toggle('night',m==='night');document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===m));if(!scene)return;scene.background.set(m==='day'?'#dce9e2':m==='sunset'?'#e7cbb0':'#273f4b');coast.setMode(m);sun.color.set(m==='day'?'#fff4d7':m==='sunset'?'#ffd09a':'#b2d0e4');sun.intensity=m==='night'?.85:2.2;sun.position.set(m==='sunset'?-650:-400,m==='sunset'?200:700,350);ambient.intensity=m==='night'?.85:2;}
function select(i,manual=true){selected=Math.max(0,Math.min(STOPS.length-1,i));if(manual&&touring){paused=true;$('#pause').textContent='계속';}panel();setMode(STOPS[selected].mode);focus();$(`[data-stop="${selected}"]`).scrollIntoView({inline:'nearest',block:'nearest',behavior:'instant'});}
function fly(target,zoom){if(!camera)return;const offset=flat?new T.Vector3(0,1000,.1):new T.Vector3(630,740,950);flight={t:performance.now(),a:camera.position.clone(),b:target.clone().add(offset),ta:controls.target.clone(),tb:target,za:camera.zoom,zb:zoom};if(reduced){camera.position.copy(flight.b);controls.target.copy(target);camera.zoom=zoom;camera.updateProjectionMatrix();flight=null;}}
function focus(){if(!camera)return;const [x,z]=STOPS[selected].camera;fly(new T.Vector3(x,15,z),innerWidth<701?.8:1.6);}
function overview(){fly(new T.Vector3(innerWidth<701?-30:20,0,0),innerWidth<701?.34:.8);}
function fallback(){failed=true;$('#fallback').hidden=false;$('#labels').hidden=true;$('#loading').hidden=true;if(renderer)renderer.domElement.hidden=true;document.querySelectorAll('#zoomIn,#zoomOut,#flat,#overview').forEach(b=>b.disabled=true);}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight;camera.left=-390*aspect;camera.right=390*aspect;camera.top=390;camera.bottom=-390;camera.setViewOffset(innerWidth,innerHeight,innerWidth<701?0:innerWidth*.035,innerWidth<701?innerHeight*.085:-innerHeight*.02,innerWidth,innerHeight);camera.updateProjectionMatrix();}
async function init3D(){try{T=await import('three');const [{OrbitControls},{createCoast,LOCATIONS,NAMES}]=await Promise.all([import('./vendor/OrbitControls.js'),import('./coast.js?v=0913-1')]);if(new URLSearchParams(location.search).has('flat'))throw Error('2D requested');renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;$('#world').prepend(renderer.domElement);scene=new T.Scene();scene.background=new T.Color('#dce9e2');camera=new T.OrthographicCamera(-600,600,390,-390,1,5000);camera.position.set(innerWidth<701?600:650,740,950);camera.zoom=innerWidth<701?.34:.8;controls=new OrbitControls(camera,renderer.domElement);controls.target.set(innerWidth<701?-30:20,0,0);controls.enableDamping=true;controls.dampingFactor=.06;controls.minZoom=.3;controls.maxZoom=3;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.05;controls.addEventListener('start',()=>{flight=null;if(touring){paused=true;$('#pause').textContent='계속';}});ambient=new T.HemisphereLight('#fff6e5','#7e9b85',2);scene.add(ambient);sun=new T.DirectionalLight('#fff4d7',2.2);sun.position.set(-400,700,350);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-850,right:850,top:850,bottom:-850,near:1,far:1900});sun.shadow.normalBias=1.5;scene.add(sun);coast=createCoast();scene.add(coast.root);
const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});
renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6){down=null;return;}down=null;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(coast.root,true)[0];if(!hit)return;const ranked=Object.entries(LOCATIONS).map(([id,[x,z]])=>({id,d:Math.hypot(hit.point.x-x,hit.point.z-z)})).sort((a,b)=>a.d-b.d);const a=ranked[0];if(a.d>140)return;if(a.id==='nue'){pauseForDialog();$('#guide').showModal();}else select(STOPS.findIndex(s=>s.place===a.id));});
for(const [id,[x,z]] of Object.entries(LOCATIONS)){const el=document.createElement('button');el.className='landmark';el.textContent=NAMES[id];el.setAttribute('aria-label',NAMES[id]+' 안내');el.onclick=()=>{if(id==='nue'){pauseForDialog();$('#guide').showModal();$('#guideBody').scrollTop=0;}else select(STOPS.findIndex(s=>s.place===id));};$('#labels').append(el);labels.push({id,el,point:new T.Vector3(x,id==='nue'?100:55,z)});}renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback();});resize();controls.update();setMode(mode);$('#loading').hidden=true;panel();}catch(e){fallback();if(!String(e).includes('2D requested'))console.warn('3D unavailable, using accessible 2D guide:',e);}}
let last=0,elapsed=0;
function coveredLabel(x,y){const regions=['header.title','.status','.toptools','.sceneControls','footer',...document.body.classList.contains('panelClosed')?[]:['#panel']];return regions.some(s=>{const r=$(s).getBoundingClientRect();return x+85>r.left&&x-85<r.right&&y>r.top&&y-30<r.bottom;});}
function frame(t){requestAnimationFrame(frame);const dt=Math.min((t-last)/1000,1);last=t;if(document.hidden)return;if(!reduced)elapsed+=Math.min(dt,.08);if(renderer&&!failed){coast.animate(elapsed);if(flight){const p=Math.min(1,(t-flight.t)/1100),e=p*p*(3-2*p);camera.position.lerpVectors(flight.a,flight.b,e);controls.target.lerpVectors(flight.ta,flight.tb,e);camera.zoom=T.MathUtils.lerp(flight.za,flight.zb,e);camera.updateProjectionMatrix();if(p===1)flight=null;}controls.update();renderer.render(scene,camera);labels.forEach(l=>{const p=l.point.clone().project(camera),x=(p.x+1)*innerWidth/2,y=(1-p.y)*innerHeight/2;l.el.style.transform=`translate(-50%,-100%) translate(${x}px,${y}px)`;l.el.hidden=p.z>1||x<0||x>innerWidth||y<0||y>innerHeight||coveredLabel(x,y);});}if(touring&&!paused){tourClock+=dt;$('#progress').value=tourClock/9;if(tourClock>=9){tourClock=0;if(selected===STOPS.length-1)stopTour();else select(selected+1,false);}}}
function stopTour(){touring=false;paused=false;tourClock=0;$('#tourbar').hidden=true;$('#tour').textContent='▷ 자동 투어';}
function togglePanel(){const closed=document.body.classList.toggle('panelClosed');$('#panelToggle').textContent=closed?'정보 보기':'정보 접기';$('#panelToggle').setAttribute('aria-expanded',!closed);}
function pauseForDialog(){if(touring){paused=true;$('#pause').textContent='계속';}}
window.pauseTravelTour=pauseForDialog;
for(const id of ['guide','food']){const d=$('#'+id);d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});}
fillGuide();panel();
document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>select(Number(b.dataset.stop)));
document.querySelectorAll('[data-stop]').forEach(b=>b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click();}}));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#previous').onclick=()=>select(selected-1);$('#next').onclick=()=>select(selected+1);$('#photoMode').onclick=()=>{photo=!photo;$('#photoMode').setAttribute('aria-pressed',photo);panel();};$('#panelToggle').onclick=togglePanel;$('#guideOpen').onclick=()=>{pauseForDialog();$('#guide').showModal();};$('#guideClose').onclick=()=>$('#guide').close();$('#print').onclick=()=>{$('#guide').close();window.print();};$('#home').onclick=e=>{e.preventDefault();overview();};$('#overview').onclick=overview;
$('#zoomIn').onclick=()=>{if(camera){flight=null;camera.zoom=Math.min(3,camera.zoom*1.2);camera.updateProjectionMatrix();}};$('#zoomOut').onclick=()=>{if(camera){flight=null;camera.zoom=Math.max(.3,camera.zoom/1.2);camera.updateProjectionMatrix();}};$('#flat').onclick=()=>{flat=!flat;$('#flat').setAttribute('aria-pressed',flat);$('#flat').textContent=flat?'입체 보기':'위에서';focus();};
$('#tour').onclick=()=>{if(touring)return stopTour();touring=true;paused=false;tourClock=0;if(selected===STOPS.length-1)select(0,false);$('#tourbar').hidden=false;$('#tour').textContent='■ 투어 종료';$('#pause').textContent='일시정지';panel();focus();};$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'계속':'일시정지';};$('#stop').onclick=stopTour;
addEventListener('resize',resize);await init3D();requestAnimationFrame(frame);
window.travelDiagnostics=()=>({selected,mode,touring,paused,flat,webgl:!failed,flight:!!flight,zoom:camera?.zoom,cameraPosition:camera?.position.toArray(),target:controls?.target.toArray(),drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,errors,stops:STOPS.length,labels:labels.length});
