const $=s=>document.querySelector(s);
const foodHTML=`<p class="warning"><b>16:40 이른 저녁 후보 · 미예약</b><br>섬에서는 산책만 하고, 출도 후 본토에서 식사합니다. 일요일 실제 영업·대기·마지막 주문은 업체 직접 확인 전입니다.</p><section class="foodcard"><span class="foodtag">전곡항 · 기본 식사 후보</span><h3>해금강횟집 전곡항</h3><p>항구에서 쉬다가 식사하기 좋은 동선의 후보입니다. 직접 시식한 추천이나 영업 보장은 아닙니다.</p><dl><dt>위치</dt><dd>화성시 서신면 전곡항로14번길 1-24</dd><dt>메뉴·가격 참고</dt><dd>다이닝코드 메뉴: 모듬회 소 130,000원 · 생우럭매운탕 소 60,000원 · 연포탕 소 60,000원. 수록 후기에는 회덮밥 15,000원·물회 20,000원·백합칼국수 15,000원 소개. 실제 주문 가격·세트 구성·인원은 방문 전 확인.</dd><dt>영업·주문</dt><dd>조회 화면은 토요일 05:00–24:00. 수록 후기의 ‘매일’ 표기만으로 내일 영업을 확정하지 않았습니다. 일요일 휴무·브레이크타임·마지막 주문·재료 소진 미확인.</dd><dt>주차</dt><dd>수록 후기에 상가 옆·인근 공영주차장 안내. 현재 요금·주차 여유·대형차 진입 폭은 미확인. 불법 주차 대신 허용된 주차면을 확인하세요.</dd></dl><div class="foodlinks"><a href="https://www.google.com/maps/search/?api=1&query=해금강횟집%20전곡항" target="_blank" rel="noopener noreferrer">지도·현장 사진 ↗</a><a href="tel:050713283307">전화로 확인</a><a href="https://www.diningcode.com/profile.php?rid=RE9xADgDYTak" target="_blank" rel="noopener noreferrer">메뉴·출처 원문 ↗</a></div></section><section class="foodcard"><span class="foodtag">카페 · 현장 선택</span><h3>전곡항에서 쉬어가기</h3><p>16:00–16:30 커피 휴식. 특정 업체의 일요일 운영·좌석·대형차 주차를 확인하지 못해 확정 예약 장소처럼 지정하지 않았습니다. 허용된 주차면을 먼저 확보하고, 실제 영업 중인 카페를 선택하세요.</p><a href="https://www.google.com/maps/search/?api=1&query=전곡항%20카페" target="_blank" rel="noopener noreferrer">권역 카페·사진 확인 ↗</a></section><h3>기다림이 길면</h3><p>주문 가능 여부를 확인한 본토 식당으로 바꾸거나 카페·일몰 일정을 줄입니다. 19:52 야간 개방을 기다려 섬 식당에 다시 들어가는 코스는 기본 계획에서 제외했습니다. 조개류는 충분히 익혀 드시고, 알레르기·동반 조건은 업체에 직접 확인하세요.</p><p class="smallnote">업체정보 확인: 2026.09.12 KST. 직접 전화·예약·결제 없음. 사진 재배포 권리 미확보로 원문 링크만 제공합니다.</p>`;
$('#foodBody').innerHTML=foodHTML;
$('#foodOpen').onclick=()=>{window.pauseTravelTour?.();$('#food').showModal();};$('#foodClose').onclick=()=>$('#food').close();
function attach(){const p=$('#panelBody');if(p&&!p.querySelector('.foodPanelLink')){const b=document.createElement('button');b.className='foodPanelLink';b.textContent='본토 식사·카페 후보 →';b.onclick=()=>{window.pauseTravelTour?.();$('#food').showModal();};p.append(b);}const out=$('#printAll');if(out?.children.length&&!out.querySelector('.foodPrint')){const el=document.createElement('section');el.className='foodPrint';el.innerHTML='<h2>식사 후보</h2>'+foodHTML;out.append(el);}}
new MutationObserver(attach).observe($('#panelBody'),{childList:true});attach();
// Original sine-based ambient score. No recordings, network audio, or autoplay.
let ctx,master,analyser,timer,wanted=false,enabled=false,volume=.25,beat=0,next=0,generation=0,scheduled=0;
function voice(context,destination,midi,time,duration,gain=.07){const o=context.createOscillator(),v=context.createGain();o.type='sine';o.frequency.value=440*2**((midi-69)/12);v.gain.setValueAtTime(0,time);v.gain.linearRampToValueAtTime(gain,time+.025);v.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(v);v.connect(destination);o.start(time);o.stop(time+duration+.05);o.onended=()=>{o.disconnect();v.disconnect();};}
function score(context,destination,n,t){const chords=[[48,55,60,64],[45,52,57,60],[41,48,53,57],[43,50,55,59]],melody=[72,76,79,76,74,72,67,71],bar=Math.floor(n/8)%4;if(n%8===0)chords[bar].forEach(m=>voice(context,destination,m,t,4,.055));voice(context,destination,melody[n%8],t,1.7,.075);}
function ui(){const b=$('#musicToggle');b.textContent=enabled?'♫ 음악 끄기':wanted?'♫ 대기 · 취소':'♫ 음악 켜기';b.setAttribute('aria-pressed',wanted);$('#volumeValue').textContent=Math.round(volume*100)+'%';}
function schedule(){if(!enabled||!ctx)return;while(next<ctx.currentTime+1.5){score(ctx,master,beat++,next);scheduled++;next+=.6;}}
function stop(){generation++;wanted=false;enabled=false;clearInterval(timer);timer=null;const old=ctx;ctx=null;master=null;analyser=null;if(old&&old.state!=='closed')old.close().catch(()=>{});ui();}
async function start(){if(wanted||document.hidden)return;const token=++generation;wanted=true;ui();try{const C=window.AudioContext||window.webkitAudioContext;const c=new C();ctx=c;master=c.createGain();master.gain.value=volume;analyser=c.createAnalyser();analyser.fftSize=1024;master.connect(analyser);analyser.connect(c.destination);await c.resume();if(token!==generation||!wanted||ctx!==c)return;if(c.state!=='running')throw Error('음악 실행 차단');enabled=true;beat=0;next=c.currentTime+.05;schedule();timer=setInterval(schedule,300);ui();}catch(e){stop();$('#musicToggle').title='음악 재시도: '+String(e);}}
$('#musicToggle').onclick=()=>wanted?stop():start();$('#musicVolume').oninput=()=>{volume=Number($('#musicVolume').value)/100;if(master&&ctx)master.gain.setTargetAtTime(volume,ctx.currentTime,.02);ui();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&wanted)stop();});
window.musicDiagnostics=()=>{let peak=0;if(analyser&&enabled){const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);for(const v of a)peak=Math.max(peak,Math.abs(v));}return {wanted,enabled,state:ctx?.state||'off',volume,scheduled,peak,timer:!!timer};};
window.renderMusicTest=async()=>{const c=new OfflineAudioContext(1,44100*6,44100),g=c.createGain();g.gain.value=.25;g.connect(c.destination);for(let i=0;i<6;i++)score(c,g,i,.1+i*.6);const b=await c.startRendering(),a=b.getChannelData(0);let sum=0,peak=0,finite=true;for(const v of a){finite=finite&&Number.isFinite(v);sum+=v*v;peak=Math.max(peak,Math.abs(v));}return {finite,rms:Math.sqrt(sum/a.length),peak,samples:a.length,sampleRate:b.sampleRate};};
ui();
